services:
  # Grid Trading Service
  grid-trading:
    build:
      context: .
      dockerfile: services/grid-trading/Dockerfile
    container_name: grid-trading-service
    network_mode: host
    volumes:
      - ./.grid-trading-data:/data
    environment:
      SERVER_PORT: ${GRID_PORT}
      DB_PATH: ${DB_PATH}
      ORDER_ASSURANCE_URL: ${ORDER_ASSURANCE_URL}
      SYNC_JOB_ENABLED: ${SYNC_JOB_ENABLED}
      SYNC_JOB_CRON: "0 * * * *"
      TRADING_FEE: ${TRADING_FEE}
    depends_on:
      - order-assurance
    restart: unless-stopped

  # Order Assurance Service
  order-assurance:
    build:
      context: .
      dockerfile: services/order-assurance/Dockerfile
    container_name: order-assurance-service
    network_mode: host
    environment:
      SERVER_PORT: ${ASSURANCE_PORT}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET}
      GRID_TRADING_URL: ${GRID_TRADING_URL}
    restart: unless-stopped

  # Price Monitor Service
  price-monitor:
    build:
      context: .
      dockerfile: services/price-monitor/Dockerfile
    container_name: price-monitor-service
    network_mode: host
    environment:
      SERVER_PORT: ${MONITOR_PORT}
      GRID_TRADING_URL: ${GRID_TRADING_URL}
      PRICE_CHECK_INTERVAL_MS: ${PRICE_CHECK_INTERVAL_MS}
      MIN_PRICE_CHANGE_PCT: ${MIN_PRICE_CHANGE_PCT}
    depends_on:
      - grid-trading
    restart: unless-stopped

volumes:
  grid_data: